# Base configs
baseurl: ""
url: "http://haydonlglover.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Haydon Glover"
subtitle: ""
author: "Haydon Glover"
bio: ""
publicise: ""
web_design: ""
social_urls:
  instagram: "https://www.instagram.com/haydonlglover/"
  